### For more information on these options, please visit
### https://github.com/seelabutk/vci.

### Define the data source
data:
  source: https://link-to.your-dataset.netcdf
  variables:
    - x
    - y
    - z
  target:
    path: path/to/place/dataset
  time-variable: t


### Local deployment
### Each node should have Docker Engine installed.
cluster:
  identity: path/to/ssh/identity/file # TODO: this shouldn't be in a committed file
  #managers:
  #workers:


### TODO: AWS deployment
### TODO: Terraform deployment (maybe)
