### For more information on these options, please visit
### https://github.com/seelabutk/vci.

### Define the data source
data:
  source: https://link-to.your-dataset.netcdf
  variables:
    - x
    - y
    - z
  target:
    path: path/to/place/dataset
  time-variable: t


### TODO: determine if a timeout setting here would be a good idea/possible


### Local deployment
### Each node should have Docker Engine installed.
cluster:
  identity: path/to/ssh/identity/file # TODO: this shouldn't be in a committed file
  managers:
    - IP.of.node.1
    - IP.of.node.2
  workers:
    - IP.of.node.3
    - IP.of.node.4
    - IP.of.node.5
    - IP.of.node.6


### TODO: AWS deployment
### TODO: Terraform deployment (maybe)
