### For more information on these options, please visit
### https://github.com/seelabutk/substrate.

### Define the data source
data:
  source: /path/to/your/dataset.raw
  dimensions:
    - 256
    - 256
    - 256
  #target:
  ### TODO: NetCDF support
  #variables:
  #  - x
  #  - y
  #  - z
  #time-variable: t


### Local deployment
### Each node should have Docker Engine installed.
cluster:
  port: 8080
  replicas: 30
  scale_interval: 60
  advertise_addr: leader.ip.address.here:2377
  managers:
    - ssh_username@manager2.ip.address.here
    - ssh_username@manager3.ip.address.here
  workers:
    - ssh_username@worker1.ip.address.here
    - ssh_username@worker2.ip.address.here
    - ssh_username@worker3.ip.address.here


### TODO: AWS deployment
### TODO: Terraform deployment (maybe)
