### For more information on these options, please visit
### https://github.com/seelabutk/substrate.

### Define the data source
data:
  source: https://link.to/your/dataset.raw
  dimensions:
    - 256
    - 256
    - 256
  target: /path/to/store/dataset.raw
  #variables:
  #  - x
  #  - y
  #  - z
  #time-variable: t


### Local deployment
### Each node should have Docker Engine installed.
cluster:
  port: 8080
  replicas: 2
  scale_interval: 60
  #managers:
  #workers:
